apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: shared
  description: Cross-cutting platform capabilities
spec:
  owner: "group:default/users"
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: identity
  description: Construction finance in project management
spec:
  owner: "group:default/users"
  subdomainOf: shared
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: project-management
  description: Project Management domain
spec:
  owner: "group:default/users"
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: accounting
  description: Construction finance in project management
spec:
  owner: "group:default/users"
  subdomainOf: project-management
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: product-management-system
  description: "Manages software tenant provisioning and licensing"
spec:
  owner: "group:default/users"
  domain: shared
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: product-manager
  description: "Orchestrates software tenant provisioning and licensing"
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - idesign-mgr
spec:
  type: Service
  lifecycle: experimental
  owner: "group:default/users"
  system: "product-management-system"
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-registry
  description: "Registers software tenants and locates instances"
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - idesign-resource-access
    - idesign-mgr
spec:
  type: Service
  lifecycle: experimental
  owner: "group:default/users"
  system: "product-management-system"
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: tyler-vista-test-system
  description: "A Vista construction ERP"
spec:
  owner: "group:default/users"
  domain: accounting
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tyler-vista-application
  description: "Core Vista"
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - idesign-mgr
spec:
  type: WebApp
  lifecycle: experimental
  owner: "group:default/users"
  system: "tyler-vista-test-system"
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: entitlement-management-system
  description: "Entitlement and License Management"
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: "group:default/users"
  domain: shared
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ems
  description: "Entitlement Management Service"
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - idesign-mgr
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/users"
  system: "entitlement-management-system"
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: iam-management-system
  description: "Identity and Access Management System"
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  lifecycle: experimental
  owner: "group:default/users"
  domain: identity
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: iam-manager
  description: "Identity and Access Management Public API"
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - idesign-mgr
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/users"
  system: "iam-management"
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: license-engine
  description: "Entitlement Management Service"
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - idesign-engine
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/users"
  system: "entitlement-management-system"
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: trimble-admin-system
  description: "Trimble Admin Console (Account Experience)"
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: "group:default/users"
  domain: shared
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: axp
  description: "Trimble Admin Console"
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - idesign-client
spec:
  type: WebApp
  lifecycle: experimental
  owner: "group:default/users"
  system: "trimble-admin-system"
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: onboard-manager
  description: "Onboard Manager (AXP backend)"
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - idesign-mgr
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/users"
  system: "trimble-admin-system"
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workflow-engine-system
  description: "Runs Elsa workflows"
spec:
  owner: "group:default/users"
  domain: shared
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: workflow-engine
  description: "Runs Elsa workflows"
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - idesign-engine
spec:
  type: Service
  lifecycle: experimental
  owner: "group:default/users"
  system: "workflow-engine-system"
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: dx-system
  description: "Digital Experience System"
spec:
  owner: "group:default/users"
  domain: shared
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dx-salesforce-api
  description: "Salesforce"
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - idesign-mgr
spec:
  type: Service
  lifecycle: experimental
  owner: "group:default/users"
  system: dx-system