apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-registry
  description: "Registers software tenants and locates instances"
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/users"
  system: "ProductManagement"